### ISSUE TITLE
Не блокируется libtorrent.

### ISSUE THREAD

**Issue by DarjaKalinina** [aliasxrus/torrent-manager#15]
Добрый день!

Спасибо вам за такую хорошую работу и за этот скрипт. Все работает прекрасно. 
Единственное, не блокируется какой то libtorrent. К сожалению достаточно много таких ко мне подключается. 
Есть вариант это как ты исправить?

Благодарю,
Дарья

![libtorrent](https://user-images.githubusercontent.com/86409374/123248420-93b0a900-d4f0-11eb-957d-8271577b51ca.PNG)

**Comment by aliasxrus** [comment]
Добрый день!
Можно установить версию в конфиге на libtorrent: {major: 99, minor: 99, micro: 99}, и будет блокировать.
