### ISSUE TITLE
черный список

### ISSUE THREAD

**Issue by maksisru** [aliasxrus/torrent-manager#16]
привет подскажи почему зеталинк в черном списке ? по доходности получше зомро будет
Протестированные VPS:

FirstByte
ZOMRO
Лучшие Linux сервера у REG.RU

Черный список:

Vultr (почасовая оплата)
ZetaLink

**Comment by aliasxrus** [comment]
Добрый вечер!
@maksisru слишком часто блокируют за использование торрент клиента.

**Comment by maksisru** [comment]
у меня тариф за 400 для пробы брал.  проработал месяц (пару дней остал.) хз. но после обновы пару дней назад чуть меньше сыпать стало (раза в три) а так проблем не было афк был 1 раз из за збоя на пару час.

Объясни мне .. не догоняю **блокируют** это рубят сервак, инет или как? спасиб за ранее)))

просто по сравнению с зомро доход на зеталинке раза в 3 по монетам а тои в 5 было (до обновы. опять же пару дней назад которая)

кстати на выделенном разница + раз в десять... но и цена в 10раз))) (хотя заморочек по меньше)

**Comment by aliasxrus** [comment]
Полностью отлючают сервер
