### ISSUE TITLE
не удаляет при снижении свободного места на диске

### ISSUE THREAD

**Issue by Ratiboriy** [aliasxrus/torrent-manager#37]
![photo_2021-11-02_22-33-26](https://user-images.githubusercontent.com/89318857/139941711-6ea7d4bf-0078-4e87-b0cd-264e1cc85ead.jpg)
не удаляет при снижении свободного места на диске

**Comment by aliasxrus** [comment]
@lexandr0s Привет, подскажешь?)

**Comment by Ratiboriy** [comment]
> @lexandr0s Привет, подскажешь?)
установил сервак, все папки скопировал с работающего, там удаляет - на новом ошибку эту пишет. скачал новый - он вообще игнорирует малое свободное место

**Comment by lexandr0s** [comment]
Скорее всего ошибка в настройках.

**Comment by Ratiboriy** [comment]
Ошибка была в каком то торренте, после удаления нескольких - стал получать хэш и удалять дальше
