### ISSUE TITLE
SyntaxError: Unexpected token i in JSON at position 2

### ISSUE THREAD

**Issue by imnachar** [aliasxrus/torrent-manager#5]
Привет. Имею две системы, на одной скрипт нормально работает, а на другой такая ошибка:
![ошибка](https://user-images.githubusercontent.com/69082644/116205137-a4020d00-a767-11eb-82d8-9b8d0b0f02b8.PNG)

(node:6620) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token i in JSON at position 2
    at parse (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getPeers (S:\Portable\torrent-manager-main\src\index.js:69:32)
    at async Timeout._onTimeout (S:\Portable\torrent-manager-main\src\index.js:177:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Переустанавливал Nodejs, переустанавливал скрипт, перепроверял настройки. Из браузера веб интерфейс доступен, версия веб интерфейса одна и та же на обеих системах

**Comment by aliasxrus** [comment]
Привет!
Такая ошибка возникает при отказе в доступе к WebUI. Вечером добавлю тест доступа и вывод результатов в консоль.
Пока можно попробовать сменить порт, проверить последняя версия скрипта или нет.

**Comment by imnachar** [comment]
Ок. Скрипт последней версии. Порт менял несколько раз. Файрволл выключал полностью. Даже не представляю, в чем дело. Все браузеры открывают исправно открывают веб-интерфейс

**Comment by alexander-migidin** [comment]
Приветствую!
Так же такая проблема.

**Comment by aliasxrus** [comment]
@imnachar добавил дополнительный вывод в лог. Необходимо повторить и скинуть полный текст ошибки.

**Comment by imnachar** [comment]
Скрипт обновил, ошибка:
Manager started! Scan interval: 10000
(node:8060) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token i in JSON at position 2
    at parse (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getPeers (S:\Portable\torrent-manager-main\src\index.js:70:32)
    at async Timeout._onTimeout (S:\Portable\torrent-manager-main\src\index.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aliasxrus** [comment]
@imnachar @alexander-migidin Поправил, можно пробовать. Проблема была в большом запросе к клиенту.

**Comment by imnachar** [comment]
@aliasxrus Заработало! Спасибо!
