### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by pslcb** [aliasxrus/torrent-manager#6]
![image](https://user-images.githubusercontent.com/83465510/116722256-d8373100-a9e6-11eb-91ac-5d55d70e6042.png)
[2021-04-30T15_39_08_200Z-debug.log](https://github.com/aliasxrus/torrent-manager/files/6406634/2021-04-30T15_39_08_200Z-debug.log)

PS Y:\Soft\torrent-manager-main> npm start

> torrent-manager@0.0.5 start Y:\Soft\torrent-manager-main
> node src/index.js

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- Y:\Soft\torrent-manager-main\src\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:838:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1022:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (Y:\Soft\torrent-manager-main\src\index.js:2:20)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1118:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:982:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:875:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'Y:\\Soft\\torrent-manager-main\\src\\index.js'←[39m ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! torrent-manager@0.0.5 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the torrent-manager@0.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     Y:\Users\31\AppData\Roaming\npm-cache\_logs\2021-04-30T15_39_08_200Z-debug.log
PS Y:\Soft\torrent-manager-main>

Привет!
Использую Node.js v13.14.0x64 т.к. v14 на Win7 не ставится. 'fs/promises' насколько понимаю в v13 не работает, можно что-то сделать с этим?

**Comment by aliasxrus** [comment]
@pslcb Привет! Попробуй с этой ветки https://github.com/aliasxrus/torrent-manager/tree/disabled-fs-primises

**Comment by pslcb** [comment]
> @pslcb Привет! Попробуй с этой ветки https://github.com/aliasxrus/torrent-manager/tree/disabled-fs-primises

Отлично! Работает, благодарю за скорый ответ!
